### ISSUE TITLE
A request for train dataset

### ISSUE THREAD

**Issue by ForestNobear** [hay-001/MODNet-Multi-offset-Point-Cloud-Denoising-Network#2]
Thanks for your wonderful work! I saw your article that you sampled the PointFilter data set, but I downloaded the training data set of you and PointFilter and found that there was no original mesh data. So would you kindly share the mesh data of training?
I would really appreciate it!

**Comment by hay-001** [comment]
Since the dataset of our method comes from pointfilter, as far as I know, there is no mesh in the training set. If you need mesh for training, I recommend you use the dataset of [score-denoise](https://github.com/luost26/score-denoise) .
